### ISSUE TITLE
Missing assets folder for Homer

### ISSUE THREAD

**Issue by ailieff** [abhilesh/self-hosted_docker_setups#3]
Hey it would be nice if you could also commit the "assets" folder - the icons are good fit for all services. Or point to a place for those maybe?

**Comment by abhilesh** [comment]
Didn't think there was interest for the icons, but here you go, committed the `assets` folder as well - [ebdf174](https://github.com/abhilesh/self-hosted_docker_setups/commit/ebdf17403da04e4a0a08d26ab705c351ec8b02f2)

The icons for the services are located in `assets` --> `tools`.

**Comment by ailieff** [comment]
Thank you very much! Appreciate it!
