### ISSUE TITLE
Calibre-web metadata.db

### ISSUE THREAD

**Issue by viniciuspaes** [abhilesh/self-hosted_docker_setups#7]
Hi Abhilesh! In my first run with calibre web i got an error 500.

In further inspection, I noticed that Calibre was unable to find metadata.db in /books.

I was able to download a sample for metadata.db from: https://github.com/linuxserver/docker-calibre-web/issues/30#issuecomment-1370898505

After that, everything works fine.

**Comment by abhilesh** [comment]
Thanks a lot for bringing this to my attention and I'm glad you could successfully install calibre web. 

The `metadata.db` file issue seems to be a common one, there's also file permissions issues that sometimes lead to unsuccessful installations, especially on docker. 

The [janeczku/calibre-web](https://github.com/janeczku/calibre-web) repo also has an empty [metadata.db](https://github.com/janeczku/calibre-web/blob/master/library/metadata.db) file included.

**Comment by viniciuspaes** [comment]
In case anyone is interested in replicating your setup, do you think it is plausible to add the metadata.db file in your repository and update docker-compose.yml file stating that the metadata.db should be placed in the /books, to avoid error 500? Just a sugestion.

**Comment by abhilesh** [comment]
Thanks a lot! Added the `metadata.db` file and instructions to the repo with this [commit](https://github.com/abhilesh/self-hosted_docker_setups/commit/06f5d7fc7a2bc180f7d8057b1b69793c9557e91b).
